name: "Build and test"

on: push

jobs:
  build-linux:
    name: Build Linux
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8"]
        os: [ubuntu-20.04]
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install linux packages"
        run: sudo apt-get update && sudo apt-get install build-essential swig -y
      - name: "Create virtual Environment"
        run: python3 -m venv .venv
      - name: "Install python packages"
        run: source .venv/bin/activate && pip3 install wheel setuptools
      - name: "Build package"
        run: |
          source .venv/bin/activate
          python setup.py bdist_wheel
          mv dist/*.whl .
          echo "WHL_NAME=$(ls *.whl)" >> $GITHUB_ENV
      - name: "Upload python wheel"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.WHL_NAME }}
          path: ${{ env.WHL_NAME }}

  build-windows:
    name: Build Windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7","3.8","3.9","3.10","3.11"]
        os: [windows-2019]
    permissions:
      actions: read
      contents: read
      security-events: write
    env:
      MPLBACKEND: agg
    steps:
      - name: Checkout code
        uses: nschloe/action-checkout-with-lfs-cache@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/bskPkgRequired.txt'
      - name: Choco help
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: -h
      - name: "Install swig and cmake"
        shell: pwsh
        run: choco install swig cmake -y
      - name: "Create python virtual env"
        shell: pwsh
        run: python -m venv venv
      - name: "Install wheel and conan package"
        shell: pwsh
        run: >
          ./venv/Scripts/activate.ps1 &&
          pip3 install wheel pytest setuptools &&
          python build_wheel.py -n > wheel_name.txt
      - name: "Add basilisk and cmake path to env path"
        shell: pwsh
        run: |
          $WHL_NAME = (Get-Content wheel_name.txt)
          echo "WHL_NAME=$WHL_NAME" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      - name: "Build basilisk"
        shell: pwsh
        run: >
          ./venv/Scripts/activate.ps1 &&
          python conanfile.py &&
          python build_wheel.py
      - name: "Upload python wheel"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.WHL_NAME }}
          path: ${{ env.WHL_NAME }}
   