name: Build

on: [push, pull_request]

jobs:
  # build_wheels:
  #   name: Build wheels on ${{ matrix.os }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-20.04, windows-2019, macos-11]
  #       # os: [ubuntu-20.04]

  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0  # Optional, use if you use setuptools_scm

  #     - name: Build wheels
  #       uses: pypa/cibuildwheel@v2.13.0
  #       # env:
  #       #   CIBW_PLATFORM: linux
  #       #   CIBW_ARCHS: x86_64
  #       # with:
  #       #   package-dir: .
  #       #   output-dir: wheelhouse
  #       #   config-file: "{package}/pyproject.toml"

  #     - uses: actions/upload-artifact@v3
  #       with:
  #         path: ./wheelhouse/*.whl
  
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Optional, use if you use setuptools_scm

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz

  upload_all:
    needs: [build_wheels, make_sdist]
    runs-on: ubuntu-latest
    environment: "PyPI deployement"
    # if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - name: Upload to TestPyPI
      uses: pypa/gh-action-pypi-publish@v1.8.6
      with:
        repository-url: https://test.pypi.org/legacy/
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
